### ISSUE TITLE
Capture line frequency

### ISSUE THREAD

**Issue by blalor** [boblemaire/IoTaWatt#121]
Is it possible to record the actual frequency of the input voltage? This can be used to infer power grid health. It should be close to a base value (like 60Hz), but could vary, and it would be interesting to measure that over time.

**Comment by boblemaire** [comment]
IoTaWatt measures frequency, but doesn't record it in the datalog.  That's a lot of data.  There is  presently room in the datalog for an additional set of data points for each channel.  Present thinking is to use that for power-factor, but of course there is no PF for a voltage channel, so maybe it could go there.

Frequency calculation has a resolution of about 0.2% (60Hz) due to the sample rate.  Zero crossing is only checked about every 23us.

The current frequency of channel zero is reported in the status screen to one decimal position. While not plausible, additional VT inputs could be monitoring voltages with different frequencies (line, generator).  You can get that to more precision by issuing the status request API on a regular basis and recording the values yourself or uploading to a server with a bash script or something.  The api is:
`http://iotahome.local/status?stats=yes`
Json output will look something like this:
`{"stats":"cyclerate":642.5326,"chanrate":39.98794,"runseconds":385853,"stack":17928,"version":"02_02_27","frequency":59.99025}}`

Once again, there are a lot of decimal places, but the real accuracy is 2 at best.
