### ISSUE TITLE
Wiki Configuring Direct for 3 phases

### ISSUE THREAD

**Issue by daniwebCH** [boblemaire/IoTaWatt#161]
Hi,
on my case I can not see the complete pictures ;-(

When will be those adapters be needed?

PS: I think that in europe are different countries (like Switzerland) where 3 phases installations are used in all houses.

Sorry it is not really a sw issue, but it is the only way to report it ;-)

**Comment by boblemaire** [comment]
You can ask about this at [https://community.iotawatt.com/](https://community.iotawatt.com/)
There are quite a few IoTaWatt with three phase in Switzerland, Germany, Belgium, and Australia. The adapters shown in the wiki are for direct reference.  I would recommend trying Derived reference (one VT) and see if it's accurate enough for you.  Very good results have been reported by a few users, and more importantly, there have been no reports of poor results.  It is much simpler and less expensive.

The adapters are simple and easy to make, but I cannot sell them because it would cost thousands of dollars to get the necessary safety approvals.  I will put the latest schematic and Eagle file in the Github.  Maybe I'll design a through hole version for DIY and sell the bare PCB board.

Try the Derived reference.  Follow up on the forum mentioned above.
