### ISSUE TITLE
Future Version / Feature Suggestions

### ISSUE THREAD

**Issue by deggle** [boblemaire/IoTaWatt#305]
Is there any ongoing development of this project? It looks like the best energy monitoring option available, especially with the good number of channels. However, I'd like to make some minor suggestions that I think could really improve this project and be the basis for a V2 hardware/firmware. 

You've done the hard work, so I don't actually think these suggestions would be hard to implement and could result in a real uplift in interest and sales among the home automation community.

- Migrate to ESP32 which should give some performance gains
- Use WT32-ETH01 or another option to provide wired ethernet
- Include option to post data to an MQTT broker

Is anything like this on a roadmap?

**Comment by boblemaire** [comment]
There is an ESP32 prototype.
Wired ethernet is not possible due to ESP hardware constraints
MQTT output is feasible with the ESP8266 version and not currently on the short list of ESP32 tasks to finish.

There is an HA automation currently available.

As none of this is actionable right now, I'm going to close it out.  There are threads on the[ IoTaWatt forum](https://community.iotawatt.com/) that deal with all of these subjects.
