### ISSUE TITLE
feature - influxdb2 - multiple metrics per "device"

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [boblemaire/IoTaWatt#327]
When setting measurements, you can only have a single measurement with the same $name value.

Lets say, I want to export the current wattage for each of the connected CTs. 

So, I create a measurement for each CT, set the measurements' name to something which identifies the CT, and specify the value as the CT's watts.

Everything works great.

BUT, now, lets say, I also want to export WH, or PF, or another metric.

I would have to set the $name to be a different value. In influx, this means, instead of having..... Say-

ac.watts
ac.wh
kitchen.watts
kitchen.wh

I would have something...

ac_watts.watts
ac_wh.wh
kitchen_w.watts
kitchen_wh.wh

which means there is a difficulty in selecting all of the metrics related to a single "device", as I have to set the names different.

Some ideas I have which would assist / help this problem-

1. Could re-enable the ability to have duplicate names. This was possible sometime last year.
2. An additional variable which can be defined on the measurements tab, which we can use as the measurement.

**Comment by boblemaire** [comment]
This is a bug in the configuration app caused by a typo during limited cleanup effort.  It was reported and corrected in the git several months ago and will go out in the next release due in the Fall.  In the meantime you can download and install the corrected file index.htm from the master branch to allow specifying multiple measurements with the same name.  The firmware supports that functionality.
